import React, { ReactNode } from 'react';
import 'tailwindcss/tailwind.css';
import Footer from './Footer/Footer';
import Providers from "./Providers";

interface LayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Empleotecnic",
  description: "Generated by create next app",
};

const Layout: React.FC<LayoutProps> = ({ children }) => {
  return (
    <div className="bg-gray-100 min-h-screen">
      <main >
        {children}
      </main>
      <Footer/>
    </div>
  );
};

export default Layout;